### ISSUE TITLE
Default units support

### ISSUE THREAD

**Issue by kof** [cssinjs/istf-spec#3]
For e.g. in react we can omit 'px' for many values.

**Comment by geelen** [comment]
Big 👎 from me. Most CSS values have no sensible default unit. Pixels are most commonly used but they're not "preferred".

**Comment by kof** [comment]
> Most CSS values have no sensible default unit

So is there anything that stops us from defining sensible defaults? Btw. [jss-default-unit](https://github.com/cssinjs/jss-default-unit/blob/master/src/defaultUnits.js) defines different defaults for different props.

**Comment by kof** [comment]
The benefit of having it is 

- typings
- smaller payload

**Comment by geelen** [comment]
As in, the properties intrinsicly _don't have_ sensible defaults. There's no reason to bless `px` over `rem` for margins or font-sizes, for instance. Line heights can be unitless. I've expanded a bit on this idea here: https://github.com/styled-components/styled-components/issues/825#issuecomment-303864178

**Comment by kof** [comment]
Alright then lets put this one on hold for now.

**Comment by kof** [comment]
I would argue that within one project there can be sensible defaults for default units, but, in the context of a cross-package standard there is no. Every package would need to define its default units , which is a bit too much overhead right now.
