### ISSUE TITLE
Document different kinds of selector-combinators

### ISSUE THREAD

**Issue by kitten** [cssinjs/istf-spec#32]
I must admit I can't with certainty tell what the ones except the first one are. I could probably figure this out by thinking about all the different combinators a bit more, but it made me realise that the spec needs a section on what they are :wink:

```js
const SPACE_COMBINATOR = 5
const DOUBLED_CHILD_COMBINATOR = 6
const CHILD_COMBINATOR = 7
const NEXT_SIBLING_COMBINATOR = 8
const SUBSEQUENT_SIBLING_COMBINATOR = 9
```

cc @kof

**Comment by kof** [comment]
terminology is taken from the spec

**Comment by kof** [comment]
https://drafts.csswg.org/selectors/#combinators

**Comment by kitten** [comment]
Ah! Perfect thanks 😅
